### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kty990** [kty990/JavaScript_GameEngine#1]
- [ ] Lighting
    - [ ] Shadows
    - [ ] Feathering
    - [x] Light overlap
- [ ] Particles
    - [ ] Emitter
    - [ ] Path(s)
    - [ ] Lifetime
- [x] Entities
- [x] Rendering
- [x] Updates
- [ ] Fluids
    - [ ] Platformer fluids w/ wave physics
    - [ ] Isometric fluids, unless height map included fluids don't move 
- [ ] Event System
    - [ ] Accessibility (Game wide, Local)
    - [ ] Structure: {timestamp: number, data: any, origin: string}
- [ ] Input Handling
    - [x] Keyboard
    - [x] Mouse
    - [ ] Gamepad
    - [x] Touch
- [ ] UI
    - [ ] Opacity
    - [ ] Replace color
    - [ ] Loaded via image
    - [ ] Loaded via pixels
    - [ ] Created via UI class
